{
 "title": "Main Boardd",
 "tags": [ "OS" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(node_exporter_build_info, zone)"
   },
   {
    "name": "type",
    "label": "Type",
    "query": "label_values(node_exporter_build_info{zone=~'$zone'},type)"
   },
   {
    "name": "hostname",
    "label": "Host name",
    "query": "label_values(node_exporter_build_info{zone=~'$zone', type='$type'}, hostname)"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "node_network_device_id{instance=~\"$instance\",  interface!=\"lo\", zone=~\"$zone\",  type=~\"$type\",  hostname=~\"$hostname\"}"
   }
  ]
 },
 "panels": [
  { "title": "Basic System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Load 1m",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) /  count(count(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load 5m",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) /  count(count(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load 15m",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load15{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) /  count(count(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used{ type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} - node_memory_SwapFree_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) / (node_memory_SwapTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} )) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{type=~\"$type\",mountpoint=\"/\",fstype!=\"rootfs\", zone=~\"$zone\", hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} - node_boot_time_seconds{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg by (mode)(irate(node_cpu_seconds_total{mode='iowait',type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])) * 100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "avg by (mode)(irate(node_cpu_seconds_total{mode=\"system\",type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "avg by (mode)(irate(node_cpu_seconds_total{mode='user',type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "avg by (mode)(irate(node_cpu_seconds_total{mode='idle',type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])) * 100",
     "legendFormat": "Idle "
    },
    {
     "expr": "avg by (mode)(irate(node_cpu_seconds_total{mode='nice', type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])) * 100",
     "legendFormat": "Nice"
    }
   ]
  },
  {
   "title": "CPU_used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (avg by(instance, job, env, nameserver, gamecode) (irate(node_cpu_seconds_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\",mode=\"idle\"}[5m]))))*100",
     "legendFormat": "CPU used"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(node_intr_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} - node_memory_MemFree_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} - (node_memory_Cached_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} + node_memory_Buffers_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} + node_memory_Buffers_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} - node_memory_SwapFree_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "Percent(%)" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemFree_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} + node_memory_Buffers_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"} + node_memory_Cached_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) / node_memory_MemTotal_bytes{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}) * 100",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Memory Pages Swap In / Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Pages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "Pages swapped in (Read)"
    },
    {
     "expr": "rate(node_vmstat_pswpout{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])*-1",
     "legendFormat": "Pages swapped out (Write)"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{type=~\"$type\",device!~'rootfs', zone=~\"$zone\", hostname=~\"$hostname\"} * 100) / node_filesystem_size_bytes{type=~\"$type\",device!~'rootfs', zone=~\"$zone\", hostname=~\"$hostname\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "disk_io_utilisation{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "Disk I/O Utilisation: {{device}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m]) * -1",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk Saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "disk_saturation{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "Disk Saturation"
    }
   ]
  },
  {
   "title": "Disk Read/Write Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "disk_write_latency{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "disk_read_latency{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "CurrEstab - TCP Connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    }
   ]
  },
  {
   "title": "TCP Sockstat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{zone=~\"$zone\", type=~\"$type\", hostname=~\"$hostname\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{zone=~\"$zone\", type=~\"$type\", hostname=~\"$hostname\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "node_sockstat_TCP_orphan{zone=~\"$zone\", type=~\"$type\", hostname=~\"$hostname\"}",
     "legendFormat": "orphan"
    },
    {
     "expr": "node_sockstat_TCP_tw{zone=~\"$zone\", type=~\"$type\", hostname=~\"$hostname\"}",
     "legendFormat": "timewait"
    }
   ]
  },
  {
   "title": "UDP In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "UDP Sockstat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDP_inuse{zone=~\"$zone\", type=~\"$type\", hostname=~\"$hostname\"}",
     "legendFormat": "inuse"
    },
    {
     "expr": "node_sockstat_UDP_mem{zone=~\"$zone\", type=~\"$type\", hostname=~\"$hostname\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp6_InErrors{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}[5m])",
     "legendFormat": "NoPorts - Datagrams received on a port with no listener"
    }
   ]
  },
  {
   "title": "TCP SYN Cookie",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "node_netstat_TcpExt_SyncookiesSent{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    },
    {
     "expr": "node_netstat_TcpExt_SyncookiesRecv{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "node_netstat_TcpExt_SyncookiesFailed{type=~\"$type\", zone=~\"$zone\", hostname=~\"$hostname\"}",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    }
   ]
  },
  {
   "title": "Network in $interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "repeat": "interface",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$interface\"}[5m])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$interface\"}[5m])*-1",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}