alertmanager_version: 0.17.0
# alertmanager_sha256sum_url: https://github.com/prometheus/alertmanager/releases/download/v{{alertmanager_version}}/sha256sums.txt
# alertmanager_sha256sum: "sha256sum: {{lookup('url', alertmanager_sha256sum_url)}}"
