groups:
  - name: Alert Rules Server
    rules:
    - alert: "Host Down"
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Server has been down"
    - alert: "CPU Utilization"
      expr: total_cpu_utilization_system_user > 70 <= 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Total CPU utilization reaches {{ humanize $value }}%"
    - alert: "CPU Utilization"
      expr: total_cpu_utilization_system_user > 80 <= 85
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Total CPU utilization reaches {{ humanize $value }}%"
    - alert: "CPU Utilization"
      expr: total_cpu_utilization_system_user > 85
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Total CPU utilization reaches {{ humanize $value }}%"
    - alert: "Memory Usage"
      expr: memory_usage > 80 <= 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Memory used {{ humanize $value }}%"
    - alert: "Memory Usage"
      expr: memory_usage > 90 <= 95
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Memory used {{ humanize $value }}%"
    - alert: "Memory Usage"
      expr: memory_usage > 95
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Memory used {{ humanize $value }}%"
    - alert: "Disk Full"
      expr: disk_space_used > 80 <= 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Disk space of device {{$labels.device}} is {{ humanize $value }}% full"
    - alert: "Disk Full"
      expr: disk_space_used > 90 <= 95
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Disk space of device {{$labels.device}} is {{ humanize $value }}% full"
    - alert: "Disk Full"
      expr: disk_space_used > 95
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Disk space of device {{$labels.device}} is {{ humanize $value }}% full"
    - alert: "Disk IO Utilization"
      expr: disk_io_utilization > 80 <= 90
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "IO disk utilization reaches {{ humanize $value }}%"
    - alert: "Disk IO Utilization"
      expr: disk_io_utilization > 90 < 100
      for: 10m
      labels:
        severity: error
      annotations:
        summary: "IO disk utilization reaches {{ humanize $value }}%"
    - alert: "Disk IO Utilization"
      expr: disk_io_utilization >= 100
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "IO disk utilization reaches {{ humanize $value }}%"
    - alert: "Swap Space Usage"
      expr: swap_space_usage > 40 <= 50 and on() (hour() <= 17 or hour() >= 23)
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Swap used {{ humanize $value }}%"
    - alert: "Swap Space Usage"
      expr: swap_space_usage > 50 <= 60 and on() (hour() <= 17 or hour() >= 23)
      for: 10m
      labels:
        severity: error
      annotations:
        summary: "Swap used {{ humanize $value }}%"
    - alert: "Swap Space Usage"
      expr: swap_space_usage > 60 and on() (hour() <= 17 or hour() >= 23)
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "Swap used {{ humanize $value }}%"
    - alert: "Server Load"
      expr: node_load5 > 5 and on() (hour() <= 17 or hour() >= 23)
      for: 10m
      labels:
        severity: error
      annotations:
        summary: "Load average 5m is {{ humanize $value }} on server {{$labels.instance}}({{$labels.ip_priv}})"
    - alert: "Network Traffic In"
      expr: network_traffic_in / 10^6 > 700 <= 750
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Speed receive of network traffic reaches {{ humanize $value }}MB/s "
    - alert: "Network Traffic In"
      expr: network_traffic_in / 10^6 > 750 <= 800
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Speed receive of network traffic reaches {{ humanize $value }}MB/s"
    - alert: "Network Traffic In"
      expr: network_traffic_in / 10^6 > 800
      labels:
        severity: critical
      annotations:
        summary: "Speed receive of network traffic reaches {{ humanize $value }}MB/s"
    - alert: "Network Traffic Out"
      expr: network_traffic_out / 10^6 > 700 <= 750
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Speed transmit of network traffic reaches {{ humanize $value }}MB/s"
    - alert: "Network Traffic Out"
      expr: network_traffic_out / 10^6 > 750 <= 800
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Speed transmit of network traffic reaches {{ humanize $value }}MB/s"
    - alert: "Network Traffic Out"
      expr: network_traffic_out / 10^6 > 800
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Speed transmit of network traffic reaches {{ humanize $value }}MB/s"
  - name: Alert Rules Couchbase
    rules:
    - alert: "RAM Quota Used"
      expr: cb_bucket_ram_quota_percent_used > 80 <= 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "RAM quota of bucket {{$labels.bucket}} used {{ humanize $value }}%"
    - alert: "RAM Quota Used"
      expr: cb_bucket_ram_quota_percent_used > 85 <= 90
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "RAM quota of bucket {{$labels.bucket}} used {{ humanize $value }}%"
    - alert: "RAM Quota Used"
      expr: cb_bucket_ram_quota_percent_used > 90
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "RAM quota of bucket {{$labels.bucket}} used {{ humanize $value }}%"
    - alert: "Resident Bucket"
      expr: cb_bucketstats_vb_active_resident_items_ratio <= 90 != 0
      labels:
        severity: error
      annotations:
        summary: "Resident bucket {{$labels.bucket}} down to {{humanize $value}}%"
  - name: Alert Rules Service
    rules:
    - alert: "Service Down"
      expr:   sum(namedprocess_namegroup_states) by(instance, groupname, ip, ip_priv, product_code, job) == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Service {{$labels.groupname}} down on server {{$labels.instance}}({{$labels.ip_priv}})"
    # - alert: "CPU Service Usage"
    #   expr: cpu_service_usage > 70 and cpu_service_usage <= 80
    #   for: 5m
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "Service {{$labels.groupname}} used {{ humanize $value }}% of CPU on server {{$labels.instance}}({{$labels.ip_priv}})"
    # - alert: "CPU Service Usage"
    #   expr: cpu_service_usage > 80 and cpu_service_usage <= 85
    #   for: 5m
    #   labels:
    #     severity: error
    #   annotations:
    #     summary: "Service {{$labels.groupname}} used {{ humanize $value }}% of CPU on server {{$labels.instance}}({{$labels.ip_priv}})"
    # - alert: "CPU Service Usage"
    #   expr: cpu_service_usage > 85
    #   for: 5m
    #   labels:
    #     severity: critical
    #   annotations:
    #     summary: "Service {{$labels.groupname}} used {{ humanize $value }}% of CPU on server {{$labels.instance}}({{$labels.ip_priv}})"
    - alert: "CPU Service Usage"
      expr: cpu_service_usage_diff_24h > 20
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Service {{$labels.groupname}} used CPU higher than 24 hours ago ({{humanize $value}}%) on server {{$labels.instance}}({{$labels.ip_priv}})"
    - alert: "Memory Service Usage"
      expr: memory_service_usage > 70 <= 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Service {{$labels.groupname}} used {{ humanize $value }}% of memory on server {{$labels.instance}}({{$labels.ip_priv}})"
    - alert: "Memory Service Usage"
      expr: memory_service_usage > 80 <= 85
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Service {{$labels.groupname}} used {{ humanize $value }}% of memory on server {{$labels.instance}}({{$labels.ip_priv}})"
    - alert: "Memory Service Usage"
      expr: memory_service_usage > 85
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Service {{$labels.groupname}} used {{ humanize $value }}% of memory on server {{$labels.instance}}({{$labels.ip_priv}})"
    - alert: "Openfile Ratio"
      expr: namedprocess_namegroup_worst_fd_ratio > 50
      labels:
        severity: error
      annotations:
        summary: "Open file ratio of service {{$labels.groupname}} reaches {{ humanize $value }}%."
    - alert: "Process restarted"
      expr: namedprocess_namegroup_oldest_start_time_seconds != namedprocess_namegroup_oldest_start_time_seconds offset 1m
      labels:
        severity: error
      annotations:
        summary: "Service {{$labels.groupname}} has been restarted"
  - name: Alert Rules CCU
    rules:
    # - alert: "TCP Connections Established"
    #   expr: avg_tcp_estab_percentage_different_5m > 10
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "TCP connections current established lower than average 3 minutes ago ({{humanize $value}}%)."
    - alert: "TCP Connections Established"
      expr: tcp_estab_diff_1d < -30
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "TCP connections current established of {{$labels.code}}_socketID:{{$labels.sid}} lower than value on 1 day ago ( {{printf `gt_gs1_ccuEst{instance=~'%s'}` $labels.instance | query | first | value | humanize}}/{{printf `tcp_estab_offset_1d{instance=~'%s'}` $labels.instance | query | first | value | humanize}} : {{humanize $value}}% )."
    - alert: "TCP Connections Established"
      expr: tcp_estab_diff_1d > 30
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "TCP connections current established of {{$labels.code}}_socketID:{{$labels.sid}} higher than value on 1 day ago ( {{printf `gt_gs1_ccuEst{instance=~'%s'}` $labels.instance | query | first | value | humanize}}/{{printf `tcp_estab_offset_1d{instance=~'%s'}` $labels.instance | query | first | value | humanize}} : {{humanize $value}}% )."
    - alert: "TCP Connections Established"
      for: 1m
      expr: gt_gs1_ccuEst == 0
      labels:
        severity: critical
      annotations:
        summary: "TCP connections current established of {{$labels.code}}_socketID:{{$labels.sid}} down to 0."
    # - alert: "CCU "
    #   expr: avg_ccu_percentage_different_5m > 10
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "The number of CCU lower than average 3 minutes ago ({{humanize $value}}%)."
    - alert: "CCU "
      expr: ccu_diff_1d < -30
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "The number CCU of {{$labels.code}}_socketID:{{$labels.sid}} lower than 1 day ago ( {{printf `gt_gs1_ccu{instance=~'%s'}` $labels.instance | query | first | value | humanize}}/{{printf `ccu_offset_1d{instance=~'%s'}` $labels.instance | query | first | value | humanize}} : {{humanize $value}}% )."
    - alert: "CCU "
      expr: ccu_diff_1d > 30
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "The number CCU of {{$labels.code}}_socketID:{{$labels.sid}} higher than 1 day ago ( {{printf `gt_gs1_ccu{instance=~'%s'}` $labels.instance | query | first | value | humanize}}/{{printf `ccu_offset_1d{instance=~'%s'}` $labels.instance | query | first | value | humanize}} : {{humanize $value}}% )."
    - alert: "CCU "
      expr: gt_gs1_ccu == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "The number CCU of {{$labels.code}}_socketID:{{$labels.sid}} down to 0."
  - name: Alert Rules Network
    rules:
      - alert: "Network Latency Lost Package"
        expr: ping_loss_percent > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Package ping to {{$labels.target}} loss {{humanize $value}}%"
      - alert: "Response Code"
        expr: httpstats_api_status_code != 200
        labels:
          severity: error
        annotations:
          summary: "{{$labels.name}} with response code {{$value}}"
      - alert: "Response Time"
        expr: httpstats_api_total / 10^3 > 3
        labels:
          severity: error
        annotations:
          summary: "{{$labels.name}} with response time {{humanize $value}}s"
