groups:
  - name: Record Rules Server
    rules:
    - record: "total_cpu_utilization_system_user"
      expr: ((avg by(instance, job, ip, ip_priv) (irate(node_cpu_seconds_total{mode="user"}[5m]))) + (avg by(instance, job, ip, ip_priv) (irate(node_cpu_seconds_total{mode="system"}[5m])))) * 100
    - record: "memory_usage"
      expr: (1 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100
    - record: "disk_space_used"
      expr: (1 - node_filesystem_avail_bytes{device=~"/dev/.*"} / node_filesystem_size_bytes{device=~"/dev/.*"}) *100
    - record: "disk_io_utilization"
      expr: irate(node_disk_io_time_seconds_total{device!~"^(md\\\\d+$|dm-)"}[5m])
    - record: "swap_space_usage"
      expr: ((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100
    - record: "network_traffic_in"
      expr: rate(node_network_receive_bytes_total{device!="lo"}[5m])
    - record: "network_traffic_out"
      expr: rate(node_network_transmit_bytes_total{device!="lo"}[5m])
  - name: Record Rules Service
    rules:
    - record: "cpu_service_usage"
      # expr: ((sum by (groupname) (rate(namedprocess_namegroup_cpu_seconds_total[1m]))) / on (groupname) group_right namedprocess_namegroup_num_procs) * 100
      expr: ((sum by(groupname, instance, ip, ip_priv, product_code) (rate(namedprocess_namegroup_cpu_seconds_total[1m]))) / on(groupname, instance, ip, ip_priv, product_code) namedprocess_namegroup_num_procs  / on( instance, ip, ip_priv, product_code) group_left() count(count(node_cpu_seconds_total) by (cpu,groupname, instance, ip, ip_priv, product_code)) by (groupname, instance, ip, ip_priv, product_code) ) * 100
    - record: "cpu_service_usage_diff_24h"
      expr: cpu_service_usage - cpu_service_usage offset 24h
    - record: "memory_service_usage"
      expr: (namedprocess_namegroup_memory_bytes{memtype="resident"}  / on(instance, ip, ip_priv, product_code) group_left() node_memory_MemTotal_bytes) * 100
  - name: Record Rules CCU
    rules:
    # - record: "avg_ccu_percentage_different_5m"
    #   expr: ( 1 - gt_gs1_ccu / avg_over_time(gt_gs1_ccu[5m])) * 100
    # - record: "avg_tcp_estab_percentage_different_5m"
    #   expr: ( 1 - gt_gs1_ccuEst / avg_over_time(gt_gs1_ccuEst[5m])) * 100
    - record: "ccu_diff_1d"
      expr: (( gt_gs1_ccu - gt_gs1_ccu offset 1d) / gt_gs1_ccu offset 1d) * 100
    - record: "ccu_offset_1d"
      expr: gt_gs1_ccu offset 1d
    - record: "tcp_estab_diff_1d"
      expr: (( gt_gs1_ccuEst - gt_gs1_ccuEst offset 1d) / gt_gs1_ccuEst offset 1d) * 100
    - record: "tcp_estab_offset_1d"
      expr: gt_gs1_ccuEst offset 1d
  # - name: Record Rules Network
