---
- name: Create user group "prometheus"
  group:
    name: prometheus
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    group: prometheus
    create_home: yes
    home: /home/prometheus
    shell: /bin/bash
    state: present
