targets:
  alertmanagers:
    - addr: 10.11.101.3:9093
  exporters:
    ########## aws ##########
    - { addr: 13.233.72.244, hostname: ZP-Proxy1, type: c5.large, zone: ap-south-1}
    - { addr: 13.127.143.56, hostname: ZP-Proxy2, type: c5.large, zone: ap-south-1}
    - { addr: 54.179.152.146, hostname: GT_ZINGPLAYINTERNATIONAL_BILLING_SLAVE, type: r4.large, zone: ap-southeast-1}
    - { addr: 54.169.83.223, hostname: ZP-Dev02, type: t3.medium, zone: ap-southeast-1}
    - { addr: 13.251.95.17, hostname: SO6_ZINGTHAI_P13_SK17, type: c4.2xlarge, zone: ap-southeast-1}
    - { addr: 52.74.64.95, hostname: GT_ZINGPLAYINTERNATIONAL_BILLING_MASTER, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 52.77.122.14, hostname: GT_ZPT_iCaSea_DB1, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 52.76.0.143, hostname: TLM_SEA_CHAT143, type: r4.large, zone: ap-southeast-1}
    - { addr: 18.136.135.63, hostname: GT_ZPT_Kafka1, type: r5.xlarge, zone: ap-southeast-1}
    - { addr: 54.251.129.226, hostname: GT_ZPT_Kafka2, type: r5.xlarge, zone: ap-southeast-1}
    - { addr: 3.0.238.177, hostname: SO6-COTIPHU-SEA-MEMBASE, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.51.174, hostname: GT_ZINGPLAYINTERNATIONAL_CDN_SRC, type: c5.large, zone: ap-southeast-1}
    - { addr: 13.251.243.229, hostname: SO6-BidaSea-WebService1, type: c5.2xlarge, zone: ap-southeast-1}
    - { addr: 13.228.251.53, hostname: GT-ZPT-Kaeng-DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.3.101, hostname: GT_ZPT_KingSlave_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 52.221.49.83, hostname: SO6_ZINGTHAI_DUMMY_SK, type: r4.large, zone: ap-southeast-1}
    - { addr: 18.136.139.43, hostname: GT_ZPT_NewCa_DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 13.228.114.240, hostname: SO6-COCANGUA-SEA-SOCKET240, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 13.229.252.235, hostname: GT-ZP-LogTracking-DB1, type: c5.large, zone: ap-southeast-1}
    - { addr: 13.228.227.125, hostname: GT_ZPT_Farm2_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 52.74.127.107, hostname: SO6-BidaSea-Billing107, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 52.74.40.98, hostname: GT-ZPT-Kaeng-DB2, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.77.155.8, hostname: TLM_SEA_SOCKET, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 52.76.249.183, hostname: SO6_ZINGTHAI_CDN183, type: m3.2xlarge, zone: ap-southeast-1}
    - { addr: 52.76.114.24, hostname: GT_ZPT_Singapure_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 13.229.137.60, hostname: ZP-CDN-AutoScaling-Group2, type: c5.large, zone: ap-southeast-1}
    - { addr: 3.1.129.153, hostname: GT-ZP-P2-DB1, type: r5.large, zone: ap-southeast-1}
    - { addr: 18.136.3.229, hostname: GT_ZPT_NewCa_Chat1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 3.1.225.97, hostname: GT_ZPT_iCaSea_SK1, type: m5.2xlarge, zone: ap-southeast-1}
    - { addr: 52.74.122.228, hostname: SO6-ZPIMGSN-Scribe10, type: m3.large, zone: ap-southeast-1}
    - { addr: 52.74.22.157, hostname: SO6-ZPIMGSN-SK92, type: m3.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.66.186, hostname: GT-ZPT-PAYMENT-CB1, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 13.251.182.13, hostname: GT_ZPT_Farm2_Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 3.1.228.17, hostname: GT_ZPT_Pokdeng_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 13.228.185.229, hostname: GT_ZPT_Parser_CB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 52.74.98.134, hostname: SO6_ZINGTHAI_LIENG_SK134, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 13.229.249.218, hostname: ZP-CDN-AutoScaling-Group2, type: c5.large, zone: ap-southeast-1}
    - { addr: 3.1.37.255, hostname: ZP-TONGITS-DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 18.138.24.79, hostname: SO6_ZINGTHAI_DUMMY_DB, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 18.138.63.190, hostname: GT_ZPT_iCaSea_Service, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.76.236.85, hostname: GT_ZPT_Show_DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 3.1.234.143, hostname: SO6-BidaSea-MB41, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 54.254.230.115, hostname: SO6-ZPIMGSN-VPortal30, type: m3.xlarge, zone: ap-southeast-1}
    - { addr: 13.229.43.82, hostname: SO6_ZINGTHAI_CDN82, type: m3.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.83.69, hostname: SO6-BidaSea-MB164, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 18.136.24.174, hostname: GT_ZPT_Farm2_DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 13.251.140.243, hostname: GT_ZPT_Show_Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 13.250.0.136, hostname: SO6_ZINGTHAI_GEOIP, type: m3.large, zone: ap-southeast-1}
    - { addr: 52.77.73.158, hostname: TLM_SEA_BILLING+DB, type: r4.large, zone: ap-southeast-1}
    - { addr: 3.1.14.15, hostname: SO6_ZINGTHAI_P13_DB216, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 54.255.176.71, hostname: GT_ZPT_Vportal_Payment2, type: c5.large, zone: ap-southeast-1}
    - { addr: 18.136.60.194, hostname: GT-ZPT-Kaeng-SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 13.251.144.104, hostname: GT-ZP-LogTracking3, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.177.215, hostname: GT_ZPT_ShweShan_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 54.169.93.82, hostname: ZP-CDN-AutoScaling-Group2, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.76.184.25, hostname: GT-ZPT-Kaeng-Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 18.138.24.128, hostname: SO6-Carrom-MB46, type: r4.large, zone: ap-southeast-1}
    - { addr: 13.251.88.130, hostname: ZP-CDN-AutoScaling-Group2, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.76.245.162, hostname: GT-ZPT-PAYMENT-PM1, type: c3.2xlarge, zone: ap-southeast-1}
    - { addr: 3.1.228.76, hostname: SO6_ZINGTHAI_POKER_DB, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 3.0.242.168, hostname: GT-ZP-P2-SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.170.148, hostname: GT_ZPT_ShweShan_DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.83.167, hostname: GT-ZPT-PAYMENT-MYSQL-REPL1, type: r5.large, zone: ap-southeast-1}
    - { addr: 13.229.186.75, hostname: GT_ZPT_LoginPortal_DB1, type: c5.2xlarge, zone: ap-southeast-1}
    - { addr: 54.251.133.163, hostname: GT_ZPT_Vportal_Payment1, type: c5.large, zone: ap-southeast-1}
    - { addr: 3.0.161.155, hostname: GT_ZPT_MixedTen_Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.221.48.229, hostname: GT_ZPT_iCaSea_Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 18.136.183.138, hostname: GT_ZPT_Singapure_DB1, type: r5.large, zone: ap-southeast-1}
    - { addr: 18.136.148.210, hostname: GT_ZPT_NewCa_WebApp1, type: c5.large, zone: ap-southeast-1}
    - { addr: 18.136.20.199, hostname: SO6_ZINGTHAI_CDN199, type: m3.2xlarge, zone: ap-southeast-1}
    - { addr: 52.74.141.85, hostname: SO6_ZINGTHAI_POKER_SK, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 13.228.46.13, hostname: GT-ZP-Webpay1, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.77.219.33, hostname: SO6_ZINGTHAI_BILLING33, type: c4.2xlarge, zone: ap-southeast-1}
    - { addr: 52.221.242.156, hostname: GT-ZP-Billing-DB1, type: r5.xlarge, zone: ap-southeast-1}
    - { addr: 13.250.88.175, hostname: GT_ZPT_MixedTen_DB1, type: m5.xlarge, zone: ap-southeast-1}
    - { addr: 13.229.220.230, hostname: GT_ZPT_KingSlave_DB1, type: r5.large, zone: ap-southeast-1}
    - { addr: 52.77.188.238, hostname: SO6-COTIPHU-SEA-SOCKET, type: c4.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.255.119, hostname: S06_ZINGTHAI_BOOGYI_DB, type: r4.large, zone: ap-southeast-1}
    - { addr: 13.228.109.126, hostname: GT-ZPT-PAYMENT-MYSQL-MASTER1, type: m3.2xlarge, zone: ap-southeast-1}
    - { addr: 52.76.14.244, hostname: GT_ZPT_Kafka3, type: r5.xlarge, zone: ap-southeast-1}
    - { addr: 52.220.162.36, hostname: SO6-Carrom-SK145, type: r4.large, zone: ap-southeast-1}
    - { addr: 52.220.233.26, hostname: SO6-BidaSea-SK26, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 54.169.185.254, hostname: SO6_ZINGTHAI_LOGFARM254, type: r3.xlarge, zone: ap-southeast-1}
    - { addr: 52.220.202.98, hostname: SO6_SFMGSN_SEA_CHAT98, type: r3.xlarge, zone: ap-southeast-1}
    - { addr: 52.220.228.217, hostname: TLM_SEA_BATTLE217, type: r4.large, zone: ap-southeast-1}
    - { addr: 52.221.155.42, hostname: SO6-COCANGUA-SEA-MEMBASE, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 13.228.189.83, hostname: SO6-COCANGUA-SEA-CHAT, type: r4.large, zone: ap-southeast-1}
    - { addr: 52.220.35.126, hostname: SO6-COTIPHU-SEA-CHAT, type: r4.large, zone: ap-southeast-1}
    - { addr: 52.74.79.29, hostname: GT_ZPT_Show_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 3.0.151.19, hostname: GT-ZP-P2-Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 18.136.92.177, hostname: SO6_ZINGTHAI_LIENG_DB1, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 54.169.28.229, hostname: GT_ZPT_ShweShan_Billing1, type: c5.large, zone: ap-southeast-1}
    - { addr: 52.77.27.138, hostname: GT-ZPMMGSN-Shan-CB, type: r4.2xlarge, zone: ap-southeast-1}
    - { addr: 13.228.202.63, hostname: GT-ZPMMGSN-Shan-SK1, type: m4.xlarge, zone: ap-southeast-1}
    - { addr: 3.1.160.63, hostname: TLM_SEA_COUCHBASE141, type: r4.xlarge, zone: ap-southeast-1}
    - { addr: 18.136.148.80, hostname: GT_ZPT_NewCa_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 13.251.137.234, hostname: S06_ZINGTHAI_BOOGYI_SK234, type: r4.large, zone: ap-southeast-1}
    - { addr: 13.228.128.172, hostname: GT_ZPT_MixedTen_SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 13.251.229.117, hostname: GT_ZPT_Parser1, type: c5.2xlarge, zone: ap-southeast-1}
    - { addr: 52.76.218.64, hostname: GT-ZP-Billing-App2, type: c5.large, zone: ap-southeast-1}
    - { addr: 13.228.18.65, hostname: SO6-ZPIMGSN-Membase19, type: m2.4xlarge, zone: ap-southeast-1}
    - { addr: 3.0.24.143, hostname: ZP-TONGITS-SK1, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 18.138.100.197, hostname: GT-ZP-LogTracking4, type: c5.xlarge, zone: ap-southeast-1}
    - { addr: 13.228.112.3, hostname: GT_ZPT_Pokdeng_DB1, type: m5.xlarge, zone: ap-southeast-1}
    ########## gcp ##########
    - { addr: 35.247.191.167, hostname: gt-sing-monstone-billing, type: custom-2-4096, zone: asia-southeast1-a}
    - { addr: 35.198.195.62, hostname: gt-sing-monstone-db, type: custom-4-16384, zone: asia-southeast1-a}
    - { addr: 35.247.142.205, hostname: gt-sing-monstone-socket, type: custom-4-8192, zone: asia-southeast1-a}
    - { addr: 35.247.164.186, hostname: gt-zp-sing-lucky9-billing1, type: custom-2-4096, zone: asia-southeast1-a}
    - { addr: 35.247.173.175, hostname: gt-zp-sing-lucky9-db1, type: custom-4-16384-ext, zone: asia-southeast1-a}
    - { addr: 35.240.167.116, hostname: gt-zp-sing-lucky9-sk1, type: custom-4-8192, zone: asia-southeast1-a}
    - { addr: 35.187.229.1, hostname: gt-zpt-cuajo-billing1, type: custom-2-4096, zone: asia-southeast1-a}
    - { addr: 35.240.161.42, hostname: gt-zpt-cuajo-db1, type: custom-4-16384, zone: asia-southeast1-a}
    - { addr: 35.187.249.173, hostname: gt-zpt-cuajo-sk1, type: custom-4-8192, zone: asia-southeast1-a}
    - { addr: 35.197.154.56, hostname: gt-zpt-sharesys-logfarm2, type: custom-4-4096, zone: asia-southeast1-a}
    - { addr: 35.244.1.118, hostname: gt-zpt-cdn-builder1, type: n1-standard-1, zone: asia-south1-c}
    - { addr: 35.200.226.194, hostname: gt-zpt-cdn-data1, type: custom-2-4096, zone: asia-south1-c}
    - { addr: 35.200.167.160,hostname: zp-cdn-instance-group-1-5tdc, type: custom-2-4096, zone: asia-south1-c}
    - { addr: 35.200.129.11,hostname: zp-cdn-instance-group-2-t815, type: custom-2-4096, zone: asia-south1-b}
    - { addr: 35.200.231.178, hostname: gt-zpt-bida-billing1, type: n1-standard-2, zone: asia-south1-a}
    - { addr: 35.200.207.221, hostname: gt-zpt-bida-db1, type: custom-6-32768, zone: asia-south1-a}
    - { addr: 35.200.197.44, hostname: gt-zpt-bida-sk1, type: custom-4-24576, zone: asia-south1-a}
    - { addr: 35.200.195.174, hostname: gt-zpt-carrom-billing1, type: n1-standard-2, zone: asia-south1-a}
    - { addr: 35.200.209.38, hostname: gt-zpt-carrom-db1, type: custom-6-32768, zone: asia-south1-a}
    - { addr: 35.200.218.131, hostname: gt-zpt-carrom-sk1, type: custom-4-24576, zone: asia-south1-a}
    - { addr: 35.200.215.96, hostname: gt-zpt-ccn-billing1, type: custom-4-24576, zone: asia-south1-a}
    - { addr: 35.200.160.228, hostname: gt-zpt-ccn-db1, type: custom-6-28672, zone: asia-south1-a}
    - { addr: 35.200.138.245, hostname: gt-zpt-ccn-sk1, type: n1-highmem-4, zone: asia-south1-a}
    - { addr: 35.200.220.220, hostname: gt-zpt-poker-billing1, type: n1-standard-2, zone: asia-south1-a}
    - { addr: 35.200.177.27, hostname: gt-zpt-poker-db1, type: custom-6-32768, zone: asia-south1-a}
    - { addr: 35.200.252.219, hostname: gt-zpt-poker-sk1, type: custom-4-24576, zone: asia-south1-a}
    - { addr: 35.200.196.226, hostname: gt-zpt-sharesys-logfarm1, type: custom-4-4096, zone: asia-south1-a}
    - { addr: 35.200.197.243, hostname: gt-zpt-thoiloan-battle1, type: n1-standard-4, zone: asia-south1-a}
    - { addr: 35.200.175.75, hostname: gt-zpt-thoiloan-billing1, type: n1-standard-2, zone: asia-south1-a}
    - { addr: 35.200.167.201, hostname: gt-zpt-thoiloan-chat1, type: n1-standard-2, zone: asia-south1-a}
    - { addr: 35.200.212.101, hostname: gt-zpt-thoiloan-db1, type: n1-highmem-4, zone: asia-south1-a}
    - { addr: 35.200.157.245, hostname: gt-zpt-thoiloan-sk1, type: n1-standard-4, zone: asia-south1-a}
    - { addr: 35.200.157.138,hostname: zp-cdn-instance-group-1-25j0, type: custom-2-4096, zone: asia-south1-a}
    - { addr: 35.200.131.110,hostname: zp-cdn-instance-group-2-crh1, type: custom-2-4096, zone: asia-south1-a}
    - { addr: 35.198.34.92, hostname: gt-zp-brazil-login, type: custom-4-16384, zone: southamerica-east1-b}
    - { addr: 35.247.235.143, hostname: gt-zp-brazil-login-couchbase, type: custom-4-16384, zone: southamerica-east1-b}
    - { addr: 35.198.11.167, hostname: gt-zp-brazil-login-mysql, type: custom-4-16384, zone: southamerica-east1-b}
    - { addr: 35.198.39.200, hostname: gt-zp-brazil-tranca-billing1, type: custom-2-4096, zone: southamerica-east1-b}
    - { addr: 35.247.209.116, hostname: gt-zp-brazil-tranca-db1, type: custom-4-16384, zone: southamerica-east1-b}
    - { addr: 35.247.210.20, hostname: gt-zp-brazil-tranca-db2, type: custom-4-10240, zone: southamerica-east1-b}
    - { addr: 35.247.224.174, hostname: gt-zp-brazil-tranca-db3, type: custom-4-16384, zone: southamerica-east1-b}
    - { addr: 35.247.231.104, hostname: gt-zp-brazil-tranca-sk1, type: custom-4-8192, zone: southamerica-east1-b}
    - { addr: 35.247.192.87, hostname: gt-zp-brazil-tranca-sk2, type: custom-4-8192, zone: southamerica-east1-b}
    - { addr: 35.198.9.93, hostname: gt-zp-billing1, type: custom-8-16384, zone: southamerica-east1-c}
    - { addr: 35.247.233.181, hostname: gt-zpt-brazil-buraco-billing1, type: custom-2-4096, zone: southamerica-east1-a}
    - { addr: 35.198.11.87, hostname: gt-zpt-brazil-buraco-db1, type: custom-4-16384, zone: southamerica-east1-a}
    - { addr: 35.199.108.129, hostname: gt-zpt-brazil-buraco-db2, type: custom-4-16384, zone: southamerica-east1-a}
    - { addr: 35.198.38.185, hostname: gt-zpt-brazil-buraco-sk1, type: custom-4-8192, zone: southamerica-east1-a}
    - { addr: 35.247.222.82, hostname: gt-zpt-brazil-sharesys-logfarm1, type: custom-2-4096, zone: southamerica-east1-a}
    - { addr: 35.247.230.175, hostname: gt-zpt-sueca-db1, type: custom-4-16384, zone: southamerica-east1-a}
    - { addr: 35.198.5.247, hostname: gt-zpt-sueca-sk1, type: custom-4-8192, zone: southamerica-east1-a}
    - { addr: 35.247.248.165, hostname: gt-zpt-truco-billing1, type: custom-2-4096, zone: southamerica-east1-a}
    - { addr: 35.247.236.142, hostname: gt-zpt-truco-db1, type: custom-4-16384, zone: southamerica-east1-a}
    - { addr: 35.199.98.142, hostname: gt-zpt-truco-sk1, type: custom-4-8192, zone: southamerica-east1-a}
