---

- name: Start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
  register: prometheus_status

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted

- name: Reload prometheus
  command: curl -X POST http://localhost:9090/-/reload
  when: prometheus_status.stdout.find("running") != -1 #running

- name: Restart alertmanager
  service:
    name: alertmanager
    state: restarted
